### PR TITLE
examples: operationalization of the author disambiguation example

### PR DESCRIPTION
**Pull request by glouppe**
* [x] Add command line arguments for the advanced disambiguation example.
* [x] Switch to JSON format for input/output (rather than pickles), allowing for an easier use in external contexts.
* [x] Documentation.

### CODE REVIEW

**Comment by glouppe** [comment]
Okay, so the example is now properly working using JSON input/output format. I will document everything tomorrow so that you @natsheh and @MSusik can move on with your own analyses.

**Comment by glouppe** [comment]
Documentation is now complete. See https://github.com/glouppe/beard/blob/author-disambiguation-ops/examples/author_disambiguation_advanced.py#L55 for a description of the expected input format.

**Comment by glouppe** [comment]
Reviews are welcome :) @natsheh @MSusik @etzemis

**Comment by MSusik** [comment]
Clearer than previous version, :+1:

**Comment by glouppe** [comment]
Thanks for the review! @natsheh would you have time today for a second review? thanks

**Comment by natsheh** [comment]
Looks great! I just have not a critical suggestion:
it may be more interesting to use "sklearn.externals.joblib"’s replacement of pickle (joblib.dump & joblib.load), which is more efficient on big data. I have noticed that on Windows enviroment, I cannot load the pickle dump file.

**Pull request merged**
