### PR TITLE
fix: travis build

### PR DESCRIPTION
**Pull request by jacquerie**

### CODE REVIEW

**Comment by jacquerie** [comment]
@kaplun Build is passing now. A bit unsatisfactory, because I have no idea what made it work : )

So I will study a little this documentation and see what we were doing wrong: http://conda.pydata.org/docs/travis.html. Will remove "WIP" and ping you when I'm done.

**Comment by glouppe** [comment]
Just that I follow, Travis build was broken, without us changing anything?

**Comment by jacquerie** [comment]
Yes. I think I know what happened: `https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh` at some point changed the default value for the `PREFIX` parameter to `$HOME/miniconda2` (note the 2 at the end), while we were `cd`ing in `$HOME/miniconda`.

**Comment by glouppe** [comment]
Oh yeah indeed, it should be that.

**Comment by jacquerie** [comment]
@glouppe @kaplun I think that now we are fine.

**Comment by glouppe** [comment]
Thanks for the fix! (I wont be able to merge though, as I lost my write access by leaving inveniosoftware org.)

**Comment by kaplun** [comment]
Ouch! Just merged, and just read this. Of course you can stay among those with merging rights until you wish to contribute :)

**Comment by kaplun** [comment]
Ah, but I don't have rights to add you back. I can ask @tiborsimko though.

**Pull request merged**
