### PR TITLE
matching: initial release

### PR DESCRIPTION
**Pull request by MSusik**
* Introduces a matching algorithm for the results of
  disambiguation. The results are matched to the disambiguation
  that was available previously, before the run of BEARD.

Signed-off-by: Mateusz Susik <mateusz.susik@cern.ch>

### CODE REVIEW

**Comment by glouppe** [comment]
For further reference (no need to take this into account in this PR), here is another approach I did using a linear programming formulation instead of the hungarian algorithm to solve the matching problem. The possibility to add random constraints yields more freedom for modeling the problem.
https://github.com/glouppe/notebooks/blob/master/One-side%20assignment%20problem%20with%20linear%20programming.ipynb

**Comment by MSusik** [comment]
Your method probably should be added to the code as a replacement for munkres library

**Comment by kaplun** [comment]
@glouppe what is the status of this branch?

**Comment by glouppe** [comment]
Given the direction that @jacenkow has taken with invenio-beard, I think this branch will not be continued.

**Pull request closed without merging**
