### PR TITLE
fix: install scipy before scikit-learn

### LINKED ISSUE #80: Annoying install issue between scipy and scikit-learn
When running
```shell
(beard) $  pip install --no-cache-dir git+https://github.com/inveniosoftware/beard@master#egg=beard
```
in a fresh virtualenv we get:
```shell
Collecting beard from git+https://github.com/inveniosoftware/beard@master#egg=beard
  Cloning https://github.com/inveniosoftware/beard (to master) to /tmp/pip-build-FTsam1/beard
Collecting jellyfish (from beard)
  Downloading jellyfish-0.5.1.tar.gz
Collecting numpy>=1.9 (from beard)
  Downloading numpy-1.10.1.tar.gz (4.0MB)
    100% |████████████████████████████████| 4.1MB 55.5MB/s 
Collecting scikit-learn>=0.15.2 (from beard)
  Downloading scikit-learn-0.17.tar.gz (7.8MB)
    100% |████████████████████████████████| 7.8MB 29.8MB/s 
Collecting scipy>=0.14 (from beard)
  Downloading scipy-0.16.1.tar.gz (12.2MB)
    100% |████████████████████████████████| 12.2MB 57.4MB/s 
Collecting six (from beard)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting unidecode (from beard)
  Downloading Unidecode-0.04.18.tar.gz (206kB)
    100% |████████████████████████████████| 208kB 55.8MB/s 
Collecting fuzzy (from beard)
  Downloading Fuzzy-1.1.tar.gz
Installing collected packages: jellyfish, numpy, scikit-learn, scipy, six, unidecode, fuzzy, beard
  Running setup.py install for jellyfish
  Running setup.py install for numpy
  Running setup.py install for scikit-learn
    Complete output from command /home/jnotarst/.virtualenvs/beard/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-FTsam1/scikit-learn/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4HmVs6-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jnotarst/.virtualenvs/beard/include/site/python2.7/scikit-learn:
    Partial import of sklearn during the build process.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-FTsam1/scikit-learn/setup.py", line 247, in <module>
        setup_package()
      File "/tmp/pip-build-FTsam1/scikit-learn/setup.py", line 237, in setup_package
        .format(scipy_req_str, instructions))
    ImportError: Scientific Python (SciPy) is not installed.
    scikit-learn requires SciPy >= 0.9.
    Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html
    
    
    ----------------------------------------
Command "/home/jnotarst/.virtualenvs/beard/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-FTsam1/scikit-learn/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4HmVs6-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jnotarst/.virtualenvs/beard/include/site/python2.7/scikit-learn" failed with error code 1 in /tmp/pip-build-FTsam1/scikit-learn
```
that is, `pip` tries to install `scikit-learn` first, which checks for `scipy`, which isn't yet installed, so it fails.

Of course, if we install `scipy` first and then we run again that command, everything works:
```shell
(beard) $ pip install scipy>=0.14
(beard) $ pip install --no-cache-dir git+https://github.com/inveniosoftware/beard@master#egg=beard
Collecting beard from git+https://github.com/inveniosoftware/beard@master#egg=beard
  Cloning https://github.com/inveniosoftware/beard (to master) to /tmp/pip-build-VkyqKb/beard
Requirement already satisfied (use --upgrade to upgrade): jellyfish in ./lib/python2.7/site-packages (from beard)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.9 in ./lib/python2.7/site-packages (from beard)
Collecting scikit-learn>=0.15.2 (from beard)
  Downloading scikit-learn-0.17.tar.gz (7.8MB)
    100% |████████████████████████████████| 7.8MB 53.3MB/s 
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.14 in ./lib/python2.7/site-packages (from beard)
Collecting six (from beard)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting unidecode (from beard)
  Downloading Unidecode-0.04.18.tar.gz (206kB)
    100% |████████████████████████████████| 208kB 29.7MB/s 
Collecting fuzzy (from beard)
  Downloading Fuzzy-1.1.tar.gz
Installing collected packages: scikit-learn, six, unidecode, fuzzy, beard
  Running setup.py install for scikit-learn
  Running setup.py install for unidecode
  Running setup.py install for fuzzy
  Running setup.py install for beard
Successfully installed beard-0.0 fuzzy-1.1 scikit-learn-0.17 six-1.10.0 unidecode-0.4.18
```

### PR DESCRIPTION
**Pull request by jacquerie**
(closes #80)

### CODE REVIEW

**Comment by kaplun** [comment]
Mmh this currently fails on Travis because `conda` is not found...

**Comment by jacquerie** [comment]
It's probably unrelated, but let's see: we are missing a `hash -r` call between the `PATH` export and the `conda` call: http://conda.pydata.org/docs/travis.html.

**Comment by jacquerie** [comment]
Or maybe is the hardcoded value of `$HOME`: http://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables. Will continue investigating in #82.

**Comment by kaplun** [comment]
Is this hence superseeded by #82 ?

**Comment by jacquerie** [comment]
Nope, this is a different issue: #80 (the fact that `pip install --no-cache-dir git+https://github.com/inveniosoftware/beard@master#egg=beard` fails).

**Comment by jacquerie** [comment]
BTW, @tomaszgy was running into this issue as well, since that line is part of `base.requirements.txt` in `inspire-next`.

**Pull request merged**
