### PR TITLE
clustering: simplified double_metaphone blocking

### PR DESCRIPTION
**Pull request by MSusik**
Signed-off-by: Mateusz Susik <mateusz.susik@cern.ch>

### CODE REVIEW

**Comment by MSusik** [comment]
I decided to get rid of magical constants and simplify the code.

Some recalls (recall for LNFI - 0.9815)

| Strategy | Merge to first surname  | Merge to last surname | Previous strategy | This PR |
| --- | ------------- | ------------- | --- | --- | ---|
| threshold | | | | |
| 1 | 0.9902  | 0.9894  | 0.9911 | 0.9907 |
| 1000 | 0.992  | 0.9913 | 0.993 | 0.9927 |
| no | 0.9961 | 0.995 | 0.997 | 0.9966 |

**Comment by glouppe** [comment]
That's great :) 

+1 for merge once you have fixed Travis

**Comment by MSusik** [comment]
Ready to merge.

**Comment by glouppe** [comment]
Merging, thanks a lot

**Pull request merged**
